### ISSUE TITLE
CSS has side effect

### ISSUE THREAD

**Issue by Stexinator** [Vendare/DarkHeresy2E-FoundryVTT#194]
![grafik](https://github.com/user-attachments/assets/d1180ae7-1bf4-43fc-a89b-83a006ee780c)
As can be seen here the css has some side effect.

The offending rule is
```css
.subdirectory, .subdirectory .folder, .sidebar-tab .directory-list .entity, li.folder > .folder-header, .sidebar-tab .directory-list .folder + .entity, .sidebar-tab .directory-list .entity:last-child, .sidebar-tab .directory-list .directory-item {
	line-height: 34px;
}
```

**Comment by Stexinator** [comment]
This could be fixed by changing

```css
.playlists-sidebar h4 {
	height: 20px;
	margin: 0;
	text-align: left;
	word-break: break-all;
	text-overflow: ellipsis;
	white-space: nowrap;
	overflow: hidden;
}
```
Here the height is 20px instead of the line height of 34px
